
package View;

import Controller.MenuController;
import java.awt.Choice;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


public class Menu_usuario extends javax.swing.JFrame {

    private JLabel lUsuario;
    private JLabel save;
    private JTextField  name_player_field;
    private Choice save_time;
    private JButton play;
    private String escolha;
    
    public Menu_usuario() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        
         jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/menu_usuario_gif.gif")));
        
        play = new JButton();
        
        try {
            Font fonte= Font.createFont(Font.TRUETYPE_FONT, new File("img/8-bit pusab.ttf")).deriveFont(Font.PLAIN, 13);
            play.setFont(fonte);
            
        } catch (FontFormatException ex) {
            Logger.getLogger(Menu_usuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu_usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
        //Adicionando o botão para iniciar o jogo 
        play.setText("Iniciar");
        jLabel1.add(play);
        play.setBounds(540, 550, 200, 60);
        play.setToolTipText("Iniciar" ); //janela de texto que aparece quando passa o mouse sobre o botão
        
        
        //Adicionando o label escrito usuário
        lUsuario = new JLabel();
        lUsuario.setText("Usuário:");
        lUsuario.setFont( new Font( "Broadway", Font.PLAIN, 30 ) );
        lUsuario.setForeground(Color.white);
        jLabel1.add(lUsuario);
        lUsuario.setBounds(450, 222, 200, 40);
        
        //Adicionando o campo para o usuario digitar
        name_player_field = new JTextField();
        jLabel1.add(name_player_field);
        name_player_field.setBounds(615, 235, 150, 20);
        name_player_field.setFocusable(true);
        
        //Adiciando o label escrito Save automático a cada:
        save = new JLabel();
        save.setText("Save automático a cada:");
        save.setFont( new Font( "Broadway", Font.PLAIN, 15 ) );
        save.setForeground(Color.white);
        jLabel1.add(save);
        save.setBounds(390, 275, 210, 40);
        
        //Adicionando o campo para o usuário escolher o tempo de save
        save_time = new Choice();
        jLabel1.add(save_time);
        save_time.add("Escolha aqui");
        save_time.add("1 segundo");
        save_time.add("5 segundos");
        save_time.add("10 segundos");
        save_time.add("30 segundos");
        save_time.add("1 minuto");
        save_time.setBounds(615, 285, 150, 20);
        
        this.setVisible(false);
        
    }
    
    public void addController(MenuController menu_controller){
        
        //adicionando o listener do botão e do choice
        play.addActionListener(menu_controller);
        save_time.addItemListener(menu_controller);
         
    }
    
    public String getPlayerName(){
        return name_player_field.getText();
    }
    
    public JButton getPlay() {
        return play;
    }

    public Choice getSave_time() {
        return save_time;
    }
    
    public void setEscolha(String s1){
        this.escolha = s1;
    }
    
    public String getEscolha(){
        return this.escolha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCC0204 - Battle Space");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\willi\\Desktop\\main_background.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
